version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build
      - test:
          requires:
            - build

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:  echo "test 101" > File.txt
      - save_cache:
          key: v1-my-project-{{ checksum "project.clj" }}
          paths:
            - "File.txt"
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo $MY_ENV_VAR
  test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-my-project-{{ checksum "project.clj" }}
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo $MY_ENV_VAR
            chmod u+x test.sh
            ./test.sh
